version: '3'
services:

  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: ${HOSTNAME}
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      LETSENCRYPT_HOST: ${HOSTNAME}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${HOSTNAME}'
        letsencrypt['enable'] = false # Handled by nginx-proxy already
        nginx['listen_port'] = 80
        nginx['listen_https'] = false # Handled by nginx-proxy already
    expose:
      - 80
      - 443
      - 22
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
      - "/srv/gitlab/backups:/var/opt/gitlab/backups"

networks:
  default:
    external:
      name: nginx-proxy